// Generated by delombok at Fri Feb 12 21:32:08 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

import com.fasterxml.jackson.annotation.JsonProperty;

class AadInstanceDiscoveryResponse {
    @JsonProperty("tenant_discovery_endpoint")
    private String tenantDiscoveryEndpoint;
    @JsonProperty("metadata")
    private InstanceDiscoveryMetadataEntry[] metadata;
    @JsonProperty("error_description")
    private String errorDescription;
    @JsonProperty("error_codes")
    private long[] errorCodes;
    @JsonProperty("error")
    private String error;
    @JsonProperty("correlation_id")
    private String correlationId;

    @java.lang.SuppressWarnings("all")
    String tenantDiscoveryEndpoint() {
        return this.tenantDiscoveryEndpoint;
    }

    @java.lang.SuppressWarnings("all")
    InstanceDiscoveryMetadataEntry[] metadata() {
        return this.metadata;
    }

    @java.lang.SuppressWarnings("all")
    String errorDescription() {
        return this.errorDescription;
    }

    @java.lang.SuppressWarnings("all")
    long[] errorCodes() {
        return this.errorCodes;
    }

    @java.lang.SuppressWarnings("all")
    String error() {
        return this.error;
    }

    @java.lang.SuppressWarnings("all")
    String correlationId() {
        return this.correlationId;
    }
}
