// Generated by delombok at Fri Feb 12 21:32:08 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;

class AccessTokenCacheEntity extends Credential {
    @JsonProperty("credential_type")
    private String credentialType;
    @JsonProperty("realm")
    protected String realm;
    @JsonProperty("target")
    private String target;
    @JsonProperty("cached_at")
    private String cachedAt;
    @JsonProperty("expires_on")
    private String expiresOn;
    @JsonProperty("extended_expires_on")
    private String extExpiresOn;
    @JsonProperty("refresh_on")
    private String refreshOn;

    String getKey() {
        List<String> keyParts = new ArrayList<>();
        keyParts.add(StringHelper.isBlank(homeAccountId) ? "" : homeAccountId);
        keyParts.add(environment);
        keyParts.add(credentialType);
        keyParts.add(clientId);
        keyParts.add(realm);
        keyParts.add(target);
        return String.join(Constants.CACHE_KEY_SEPARATOR, keyParts).toLowerCase();
    }

    @java.lang.SuppressWarnings("all")
    public String credentialType() {
        return this.credentialType;
    }

    @java.lang.SuppressWarnings("all")
    public String realm() {
        return this.realm;
    }

    @java.lang.SuppressWarnings("all")
    public String target() {
        return this.target;
    }

    @java.lang.SuppressWarnings("all")
    public String cachedAt() {
        return this.cachedAt;
    }

    @java.lang.SuppressWarnings("all")
    public String expiresOn() {
        return this.expiresOn;
    }

    @java.lang.SuppressWarnings("all")
    public String extExpiresOn() {
        return this.extExpiresOn;
    }

    @java.lang.SuppressWarnings("all")
    public String refreshOn() {
        return this.refreshOn;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity credentialType(final String credentialType) {
        this.credentialType = credentialType;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity realm(final String realm) {
        this.realm = realm;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity target(final String target) {
        this.target = target;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity cachedAt(final String cachedAt) {
        this.cachedAt = cachedAt;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity expiresOn(final String expiresOn) {
        this.expiresOn = expiresOn;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity extExpiresOn(final String extExpiresOn) {
        this.extExpiresOn = extExpiresOn;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AccessTokenCacheEntity refreshOn(final String refreshOn) {
        this.refreshOn = refreshOn;
        return this;
    }
}
