// Generated by delombok at Fri Feb 12 21:32:08 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

import java.util.Map;

/**
 * Representation of a single user account. If modifying this object, ensure it is compliant with
 * cache persistent model
 */
class Account implements IAccount {
    String homeAccountId;
    String environment;
    String username;
    Map<String, ITenantProfile> tenantProfiles;

    public Map<String, ITenantProfile> getTenantProfiles() {
        return tenantProfiles;
    }

    @java.lang.SuppressWarnings("all")
    public String homeAccountId() {
        return this.homeAccountId;
    }

    @java.lang.SuppressWarnings("all")
    public String environment() {
        return this.environment;
    }

    @java.lang.SuppressWarnings("all")
    public String username() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, ITenantProfile> tenantProfiles() {
        return this.tenantProfiles;
    }

    @java.lang.SuppressWarnings("all")
    public Account homeAccountId(final String homeAccountId) {
        this.homeAccountId = homeAccountId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Account environment(final String environment) {
        this.environment = environment;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Account username(final String username) {
        this.username = username;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Account tenantProfiles(final Map<String, ITenantProfile> tenantProfiles) {
        this.tenantProfiles = tenantProfiles;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Account(final String homeAccountId, final String environment, final String username, final Map<String, ITenantProfile> tenantProfiles) {
        this.homeAccountId = homeAccountId;
        this.environment = environment;
        this.username = username;
        this.tenantProfiles = tenantProfiles;
    }
}
