// Generated by delombok at Fri Feb 12 21:32:09 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;

class AppMetadataCacheEntity {
    public static final String APP_METADATA_CACHE_ENTITY_ID = "appmetadata";
    @JsonProperty("client_id")
    private String clientId;
    @JsonProperty("environment")
    private String environment;
    @JsonProperty("family_id")
    private String familyId;

    String getKey() {
        List<String> keyParts = new ArrayList<>();
        keyParts.add(APP_METADATA_CACHE_ENTITY_ID);
        keyParts.add(environment);
        keyParts.add(clientId);
        return String.join(Constants.CACHE_KEY_SEPARATOR, keyParts).toLowerCase();
    }

    @java.lang.SuppressWarnings("all")
    public String clientId() {
        return this.clientId;
    }

    @java.lang.SuppressWarnings("all")
    public String environment() {
        return this.environment;
    }

    @java.lang.SuppressWarnings("all")
    public String familyId() {
        return this.familyId;
    }

    @java.lang.SuppressWarnings("all")
    public AppMetadataCacheEntity clientId(final String clientId) {
        this.clientId = clientId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AppMetadataCacheEntity environment(final String environment) {
        this.environment = environment;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public AppMetadataCacheEntity familyId(final String familyId) {
        this.familyId = familyId;
        return this;
    }
}
