// Generated by delombok at Fri Feb 12 21:32:09 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

final class ClientSecret implements IClientSecret {
    private final String clientSecret;

    /**
     * Constructor to create credential with client id and secret
     *
     * @param clientSecret
     *            Secret of the client requesting the token.
     */
    ClientSecret(final String clientSecret) {
        if (StringHelper.isBlank(clientSecret)) {
            throw new IllegalArgumentException("clientSecret is null or empty");
        }
        this.clientSecret = clientSecret;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ClientSecret)) return false;
        final ClientSecret other = (ClientSecret) o;
        final java.lang.Object this$clientSecret = this.clientSecret();
        final java.lang.Object other$clientSecret = other.clientSecret();
        if (this$clientSecret == null ? other$clientSecret != null : !this$clientSecret.equals(other$clientSecret)) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $clientSecret = this.clientSecret();
        result = result * PRIME + ($clientSecret == null ? 43 : $clientSecret.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public String clientSecret() {
        return this.clientSecret;
    }
}
