// Generated by delombok at Fri Feb 12 21:32:09 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

import com.nimbusds.oauth2.sdk.auth.JWTAuthentication;

final class ClientAssertion implements IClientAssertion {
    static final String assertionType = JWTAuthentication.CLIENT_ASSERTION_TYPE;
    private final String assertion;

    ClientAssertion(final String assertion) {
        if (StringHelper.isBlank(assertion)) {
            throw new NullPointerException("assertion");
        }
        this.assertion = assertion;
    }

    @java.lang.SuppressWarnings("all")
    public String assertion() {
        return this.assertion;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ClientAssertion)) return false;
        final ClientAssertion other = (ClientAssertion) o;
        final java.lang.Object this$assertion = this.assertion();
        final java.lang.Object other$assertion = other.assertion();
        if (this$assertion == null ? other$assertion != null : !this$assertion.equals(other$assertion)) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $assertion = this.assertion();
        result = result * PRIME + ($assertion == null ? 43 : $assertion.hashCode());
        return result;
    }
}
