// Generated by delombok at Fri Feb 12 21:32:09 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

class CurrentRequest {
    private final PublicApi publicApi;
    private boolean forceRefresh = false;

    CurrentRequest(PublicApi publicApi) {
        this.publicApi = publicApi;
    }

    @java.lang.SuppressWarnings("all")
    public PublicApi publicApi() {
        return this.publicApi;
    }

    @java.lang.SuppressWarnings("all")
    public boolean forceRefresh() {
        return this.forceRefresh;
    }

    @java.lang.SuppressWarnings("all")
    public CurrentRequest forceRefresh(final boolean forceRefresh) {
        this.forceRefresh = forceRefresh;
        return this;
    }
}
