// Generated by delombok at Fri Feb 12 21:32:09 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

import java.util.Map;

/**
 * Representation of a single tenant profile
 */
class TenantProfile implements ITenantProfile {
    Map<String, ?> idTokenClaims;

    public Map<String, ?> getClaims() {
        return idTokenClaims;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, ?> idTokenClaims() {
        return this.idTokenClaims;
    }

    @java.lang.SuppressWarnings("all")
    public TenantProfile idTokenClaims(final Map<String, ?> idTokenClaims) {
        this.idTokenClaims = idTokenClaims;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TenantProfile(final Map<String, ?> idTokenClaims) {
        this.idTokenClaims = idTokenClaims;
    }
}
