// Generated by delombok at Fri Feb 12 21:32:09 UTC 2021
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
package com.microsoft.aad.msal4j;

enum WSTrustVersion {
    WSTRUST13("//s:Envelope/s:Body/wst:RequestSecurityTokenResponseCollection/wst:RequestSecurityTokenResponse/wst:TokenType", "wst:RequestedSecurityToken"), WSTRUST2005("//s:Envelope/s:Body/t:RequestSecurityTokenResponse/t:TokenType", "t:RequestedSecurityToken"), UNDEFINED("", "");
    private String responseTokenTypePath = "";
    private String responseSecurityTokenPath = "";

    WSTrustVersion(String tokenType, String responseSecurityToken) {
        this.responseTokenTypePath = tokenType;
        this.responseSecurityTokenPath = responseSecurityToken;
    }

    @java.lang.SuppressWarnings("all")
    String responseTokenTypePath() {
        return this.responseTokenTypePath;
    }

    @java.lang.SuppressWarnings("all")
    String responseSecurityTokenPath() {
        return this.responseSecurityTokenPath;
    }
}
