 ##############################################################################
 #
 # (c) Copyright 1997-2000, SITRAKA INC.  
 # ALL RIGHTS RESERVED 
 #
 #  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED
 # AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE AND
 # WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR
 # ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE
 # AVAILABLE TO ANY OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE
 # SOFTWARE IS HEREBY TRANSFERRED.
 #
 #  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT
 # NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY SITRAKA INC.
 # OR ITS THIRD PARTY SUPPLIERS.
 #
 #  SITRAKA INC. AND ITS THIRD PARTY SUPPLIERS, ASSUME NO RESPONSIBILITY 
 # FOR THE USE OR INABILITY TO USE ANY OF ITS SOFTWARE.   THIS SOFTWARE IS 
 # PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, AND SITRAKA INC. EXPRESSLY 
 # DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO THE 
 # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 #
 # Notice:  Notwithstanding any other lease or license that may pertain to,
 # or accompany the delivery of, this computer software, the rights of the
 # Government regarding its use, reproduction and disclosure are as set
 # forth in Section 52.227-19 of the FARS Computer Software-Restricted
 # Rights clause.
 #
 # (c) Copyright 1997-2000 Sitraka Inc.  Unpublished - all
 # rights reserved under the Copyright laws of the United States.
 #
 # RESTRICTED RIGHTS NOTICE:  Use, duplication, or disclosure by the
 # Government is subject to the restrictions as set forth in subparagraph
 # (c)(1)(ii) of the Rights in Technical Data and Computer Software clause
 # at DFARS 52.227-7013.
 #
 # Sitraka Inc.
 # 260 King Street East
 # Toronto, Ontario
 # Canada M5A 4L5
 # (416) 594-1026
 # (416) 594-1919 (FAX)
 #
 # RESTRICTED RIGHTS LEGEND:  This computer software is submitted with
 # "restricted rights."  Use, duplication or disclosure is subject to the
 # restrictions as set forth in NASA FAR SUP 18-52.227-79 (April 1985)
 # "Commercial Computer Software- Restricted Rights (April 1985)."  Sitraka
 # Inc., 260 King St. E., Toronto, Ontario, Canada M5A 4L5.  If
 # the contract contains the Clause at 18-52.227-74 "Rights in Data General"
 # then the "Alternate III" clause applies.
 #
 # (c) Copyright 1997-2000 Sitraka Inc.
 # ALL RIGHTS RESERVED
 #
 ##############################################################################
 # RCSID -- $RCSfile: makefile $ $Revision: 2.128 $ $Date: 2000/11/09 20:11:27 $ $Locker: $  Sitraka Inc.

RELEASE = 363
PRODUCT = bwt
PACKAGE = bwt
INTERNAL = 0

SRC =  \
JCAWTEvent.java \
JCActionEvent.java \
JCActionListener.java \
JCAdjustable.java \
JCAdjustmentEvent.java \
JCAdjustmentListener.java \
JCAlignerLayout.java \
JCArrowButton.java \
JCButton.java \
JCButtonAdapter.java \
JCButtonEvent.java \
JCButtonListener.java \
JCCheckbox.java \
JCCheckboxGroup.java \
JCChoiceInterface.java \
JCComboBox.java \
JCComboBoxAdapter.java \
JCComboBoxEvent.java \
JCComboBoxListener.java \
JCComponent.java \
JCContainer.java \
JCEventListener.java \
JCGridLayout.java \
JCGroupBox.java \
JCHeader.java \
JCItemEvent.java \
JCItemListener.java \
JCItemSelectable.java \
JCLabel.java \
JCList.java \
JCListAdapter.java \
JCListComponent.java \
JCListEvent.java \
JCListInterface.java \
JCListListener.java \
JCMultiColumnData.java \
JCMultiColumnInterface.java \
JCMultiColumnList.java \
JCMultiColumnListComponent.java \
JCMultiColumnWindow.java \
JCOutliner.java \
JCOutlinerAdapter.java \
JCOutlinerComponent.java \
JCOutlinerEvent.java \
JCOutlinerFolderNode.java \
JCOutlinerInterface.java \
JCOutlinerListener.java \
JCOutliner2Listener.java \
JCOutlinerNode.java \
JCOutlinerNodeStyle.java \
JCProgressMeter.java \
JCScrollableInterface.java \
JCScrollbar.java \
JCScrolledWindow.java \
JCSeparator.java \
JCSerializable.java \
JCSlider.java \
JCSpinBox.java \
JCSpinBoxAdapter.java \
JCSpinBoxEvent.java \
JCSpinBoxListener.java \
JCSpinBoxString.java \
JCSplitterWindow.java \
JCTabButton.java \
JCTabManager.java \
JCTabManagerAdapter.java \
JCTabManagerEvent.java \
JCTabManagerListener.java \
JCTextAdapter.java \
JCTextArea.java \
JCTextAreaComponent.java \
JCTextAreaInterface.java \
JCTextComponent.java \
JCTextCursorAdapter.java \
JCTextCursorEvent.java \
JCTextCursorListener.java \
JCTextEvent.java \
JCTextField.java \
JCTextInterface.java \
JCTextLine.java \
JCTextListener.java \
JCTextManagerInterface.java \
JCVersion.java \
ArrowButtonConverter.java \
BWTEnum.java \
BWTUtil.java \
ButtonConverter.java \
CheckboxConverter.java \
CheckboxGroupConverter.java \
ComboBoxConverter.java \
ComponentConverter.java \
ContainerConverter.java \
GroupBoxConverter.java \
HeaderConverter.java \
Indicator.java \
LabelConverter.java \
ListConverter.java \
ListSelection.java \
MultiColumnConverter.java \
OutlinerConverter.java \
ProgressMeterConverter.java \
ScrollbarConverter.java \
ScrollbarThumb.java \
ScrolledWindowConverter.java \
SliderConverter.java \
SpinBoxConverter.java \
SpinBoxStringConverter.java \
SplitterWindowSeparator.java \
TabArrowPanel.java \
TabManagerConverter.java \
TabPageArea.java \
TabPanel.java \
TextAreaConverter.java \
TextComponentConverter.java \
TextLine.java \
Viewport.java 

102SRC = \
Focus.java 

110SRC = \
JCOutlinerPrintEvent.java \
JCOutlinerPrintListener.java \
JCOutlinerPrinter.java

BEANSRC = \
AboutEditor.java \
AlignmentEditor.java \
ArrowButtonOrientationEditor.java \
ColumnResizePolicyEditor.java \
ComboBoxStyleEditor.java \
HorizAlignmentEditor.java \
IndicatorEditor.java \
JCArrowButtonBeanInfo.java \
JCButtonBeanInfo.java \
JCCheckboxBeanInfo.java \
JCCheckboxGroupBeanInfo.java \
JCComboBoxBeanInfo.java \
JCComponentBeanInfo.java \
JCContainerBeanInfo.java \
JCGroupBoxBeanInfo.java \
JCLabelBeanInfo.java \
JCListBeanInfo.java \
JCListComponentBeanInfo.java \
JCMultiColumnListBeanInfo.java \
JCMultiColumnWindowBeanInfo.java \
JCOutlinerBeanInfo.java \
JCProgressMeterBeanInfo.java \
JCScrollbarBeanInfo.java \
JCScrolledWindowBeanInfo.java \
JCSeparatorBeanInfo.java \
JCSliderBeanInfo.java \
JCSpinBoxBeanInfo.java \
JCSpinBoxStringBeanInfo.java \
JCSplitterWindowBeanInfo.java \
JCTabManagerBeanInfo.java \
JCTextAreaBeanInfo.java \
JCTextComponentBeanInfo.java \
JCTextFieldBeanInfo.java \
ListRowHeightEditor.java \
OrientationEditor.java \
ProgressMeterLabelPosEditor.java \
ScrollbarDisplayEditor.java \
ShadowTypeEditor.java \
StringCaseEditor.java \
TabManagerColorPolicyEditor.java \
TabShapeEditor.java \
TabSideEditor.java 

OBSOLETE = \
ImageDisabler.java \
BWTCallback.java \
BWTCallbackInfo.java \
JCComboBoxInfo.java \
JCListInfo.java \
JCOutlinerActionInfo.java \
JCOutlinerInfo.java \
JCSpinBoxInfo.java \
JCTabManagerInfo.java \
JCTextCursorInfo.java \
JCTextValueInfo.java

CLASSES = $(SRC:.java=.class)
102CLASSES = $(102SRC:.java=.class)
110CLASSES = $(110SRC:.java=.class)
BEANCLASSES = $(BEANSRC:.java=.class)

JAVAC = $(JDKHOME)/bin/javac 
JAR = $(JDKHOME)/bin/jar 

DISTDIR = ./

first: $(JDK)

all_classes: contrib util base cell $(JDK) demo_examples

all: $(CLASSES)

102: $(CLASSES) $(102CLASSES)

110: $(CLASSES) $(110CLASSES) bean resource

SWING swing: 110
JFC jfc: 110

resource:
	(cd "resources"; make "JAVAC=$(JAVAC)")

102_checkout: pj co $(SRC) $(102SRC)
110_checkout: pj co $(SRC) $(BEANSRC)
checkout: pj co $(SRC) $(BEANSRC)

102_src:
	rm -f *.java.bak; \
	perl ../util/make102.perl `ls *.java`; \
	rm -f *.java.bak

110_src:
	rm -f *.java.bak; \
	perl ../util/make110.perl `ls *.java`; \
	rm -f *.java.bak

SWING_src swing_src:
	rm -f *.java.bak; \
	perl ../util/makeswing.perl `ls *.java`; \
	rm -f *.java.bak

JFC_src jfc_src:
	rm -f *.java.bak; \
	perl ../util/makejfc.perl `ls *.java`; \
	rm -f *.java.bak

nolite:
	rm -f *.java.bak; \
	perl ../build-tools/nolite.perl `grep -l LITE_START *.java`; \
	rm -f *.java.bak

lite:
	rm -f *.java.bak; \
	perl ../build-tools/makelite.perl `grep -l LITE_START *.java`; \
	rm -f *.java.bak

unlite:
	rm -f *.java.bak; \
	perl ../build-tools/unlite.perl `grep -l LITE_START *.java`; \
	rm -f *.java.bak

limit:
	rm -f *.java.bak; \
	perl ../build-tools/makelimit.perl `grep -l LIMIT_START *.java`; \
	rm -f *.java.bak

unlimit:
	rm -f *.java.bak; \
	perl ../build-tools/makeunlimit.perl `grep -l LIMIT_START *.java`; \
	rm -f *.java.bak

bean: $(BEANCLASSES)
	(cd "../beans"; make "JAVAC=$(JAVAC)")

contrib:
	(cd "../contrib"; make "JAVAC=$(JAVAC)")

util:
	(cd ../util; make "JAVAC=$(JAVAC)")

base:
	(cd ../base; make "JAVAC=$(JAVAC)")

cell:
	(cd ../cell; make "JAVAC=$(JAVAC)" $(JDK))

demo_examples:
	(cd "demos"; make "JAVAC=$(JAVAC)" )
	(cd "examples"; make "JAVAC=$(JAVAC)" $(JDK))
	(cd "../util/examples"; make "JAVAC=$(JAVAC)")

archive_102: zip
archive_110: jar zip
archive_SWING: jar zip
archive_JFC: jar zip

JD_KL_API = \
	jclass.bwt \
	jclass.util \
	jclass.contrib \
	jclass.base \
	jclass.cell

JD_SUN_API = \
	java.util \
	java.lang \
	java.applet \
	sunw.io \
	sunw.util \
	java.awt \
	java.awt.event

JAVADOC_SOURCEPATH = .;$(JDKHOME)/lib/classes.zip;../..;$(JDKHOME)/src;$(DOC_EXTRAPATH)
JAVADOC_FLAGS = -mx50m -ms45m
JAVADOC12_FLAGS = -mx128m -ms35m

JAVADOC = $(JDKHOME)/bin/java $(JAVADOC_FLAGS) sun.tools.javadoc.Main

JAVADOC110 = $(JAVADOC)
JAVADOC102 = $(JAVADOC)
JAVADOCSWING = $(JAVADOC)
JAVADOCJFC = $(JDKHOME)/bin/java $(JAVADOC12_FLAGS) com.sun.tools.javadoc.Main -1.1 

doc102 doc110 docJFC docSWING: doc

doc:
	rm api/*.html; \
	cp $(DOCFILES)/html/* api; \
	cp -r ../../javadoc_include/image* api; \
	cp ../../javadoc_include/*.html api; \
	cp $(DOCFILES)/html/images/* api/images; \
	mkdir hold; \
	mv -f *BeanInfo.java hold; \
	mv -f *Editor.java hold; \
	$(JAVADOC$(JDK)) -sourcepath "$(JAVADOC_SOURCEPATH)" -d api $(JD_SUN_API) $(JD_KL_API); \
	mv -f hold/* .; \
	rmdir hold

JARFILE110= lib/jc${PRODUCT}${RELEASE}.jar
JARFILESWING= lib/jc${PRODUCT}${RELEASE}S.jar
JARFILEJFC= lib/jc${PRODUCT}${RELEASE}J.jar
jar:
	cd ../..; \
	rm -f $(JARFILE$(JDK)); \
	cat jclass/bwt/manifest-beans.txt jclass/bwt/manifest-depends.txt > manifest.tmp; \
	$(JAR) cfm $(JARFILE$(JDK)) \
		manifest.tmp \
		jclass/bwt/*.class \
		jclass/bwt/*.gif \
		jclass/bwt/resources/*.class \
		jclass/util/*.class \
		jclass/util/resources/*.class \
		jclass/beans/*.class \
		jclass/base/*.class \
		jclass/cell/*.class; \
	rm manifest.tmp

ZIPFILE110= lib/jc${PRODUCT}${RELEASE}-classes.zip
ZIPFILESWING= lib/jc${PRODUCT}${RELEASE}S-classes.zip
ZIPFILEJFC= lib/jc${PRODUCT}${RELEASE}J-classes.zip
ZIPFILE102= lib/jc${PRODUCT}${RELEASE}T-classes.zip
ZIPFLAG102= -u -n class
ZIPFLAG110= -u
ZIPFLAGSWING = -u
ZIPFLAGJFC = -u
ZIP=zip

ZIPFILES = \
	jclass/bwt/*.class \
	jclass/util/*.class \
	jclass/base/*.class \
	jclass/cell/*.class

ZIPFILES_110 = \
	$(ZIPFILES) \
	jclass/bwt/resources/*.class \
	jclass/beans/*.class \
	jclass/util/resources/*.class

ZIPFILES_SWING = \
	$(ZIPFILES_110)

ZIPFILES_JFC = \
	$(ZIPFILES_110)

ZIPFILES_102 = \
	$(ZIPFILES) \
	sunw/util/*.class \
	sunw/io/*.class
 
zip:
	echo "Creating Zip File"; \
	cd ../..; \
	rm -f $(ZIPFILE$(JDK)); \
	$(ZIP) $(ZIPFLAG$(JDK)) $(ZIPFILE$(JDK)) $(ZIPFILES_$(JDK))

TARFILE110= lib/jc${PRODUCT}${RELEASE}-classes.tar
TARFILESWING= lib/jc${PRODUCT}${RELEASE}S-classes.tar
TARFILEJFC= lib/jc${PRODUCT}${RELEASE}J-classes.tar
TARFILE102= lib/jc${PRODUCT}${RELEASE}T-classes.tar

tarz:

old_tarz:
	cd ../..; \
	rm -f $(TARFILE$(JDK)) $(TARFILE$(JDK)).Z; \
	tar cf $(TARFILE$(JDK)) $(ZIPFILES_$(JDK)); \
	compress $(TARFILE$(JDK))

ARCHFILES = \
$(ZIPFILE$(JDK)) \
readme-${PRODUCT}.txt \
readme-${DISTNAME${JDK}}.txt \
jclass/bwt/demos/Makefile \
jclass/bwt/demos/*.html \
jclass/bwt/demos/images/* \
jclass/bwt/demos/awt_vs_bwt/* \
jclass/bwt/demos/colorpicker/* \
jclass/bwt/demos/printdlogs/* \
jclass/bwt/demos/launcher/* \
jclass/bwt/examples/*.html \
jclass/bwt/examples/Makefile \
jclass/bwt/examples/*.class \
jclass/bwt/examples/*.java \
jclass/contrib/Makefile \
jclass/contrib/*.java \
jclass/contrib/*.class \
jclass/util/examples/*.java \
jclass/util/examples/*.class \
jclass/util/examples/Makefile \
jclass/util/examples/*.html \
jclass/util/examples/*.gif \
jclass/bwt/images/*.gif 

API = \
jclass/bwt/api/*.html \
jclass/bwt/api/*.gif \
jclass/bwt/api/images/* \
jclass/bwt/api/images-awt/*
 
ARCHFILES_102 = \
$(ARCHFILES) \
sunw/io/* \
sunw/util/*
    
ARCHFILES_110 = \
$(JARFILE$(JDK)) \
$(ARCHFILES)

ARCHFILES_JFC = \
	$(ARCHFILES_110)

ARCHFILES_SWING = \
	$(ARCHFILES_110)

SOURCEFILES = \
jclass/bwt/*.java \
jclass/bwt/Makefile \
jclass/util/*.java \
jclass/util/*.perl \
jclass/util/Makefile \
jclass/base/*.java \
jclass/base/Makefile \
jclass/cell/*.java \
jclass/cell/Makefile

SOURCEFILES_102 = \
$(SOURCEFILES) 

SOURCEFILES_110 = \
$(SOURCEFILES) \
jclass/bwt/resources/*.java \
jclass/bwt/resources/Makefile \
jclass/bwt/manifest.txt \
jclass/util/resources/Makefile \
jclass/util/resources/*.java \
jclass/beans/*.java \
jclass/beans/Makefile

SOURCEFILES_JFC = \
	$(SOURCEFILES_110)

SOURCEFILES_SWING = \
	$(SOURCEFILES_110)

DISTNAME102=${PRODUCT}${RELEASE}T
DISTNAME110=${PRODUCT}${RELEASE}
DISTNAMESWING=${PRODUCT}${RELEASE}S
DISTNAMEJFC=${PRODUCT}${RELEASE}J

DISTFILE110=$(DISTDIR)jc${PRODUCT}${RELEASE}
DISTFILE102=$(DISTDIR)jc${PRODUCT}${RELEASE}T
DISTFILESWING=$(DISTDIR)jc${PRODUCT}${RELEASE}S
DISTFILEJFC=$(DISTDIR)jc${PRODUCT}${RELEASE}J

DOCFILES=$(DOC_DRIVE)/jclass_docs/bwt/jcbwt$(RELEASE)

.IF $(INTERNAL) == 1
include ../Makefiles/dist.mk
.END

%.class: %.java
	$(JAVAC) $(JAVACFLAGS) $<

tags:
	etags $(SRC) $(BEANSRC)

clean:
	rm -f *.class

real_clean:
	rm -f *.class; \
	rm -f resources/*.class

102_clean:
	rm -f $(OBSOLETE) $(110CLASSES) $(BEANCLASSES) $(BEANSRC)

110_clean:
	rm -f $(OBSOLETE)

obs_clean:
	rm -f $(OBSOLETE)







